AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sns-event-to-newrelic

Globals:
  Function:
    Timeout: 3

Resources:
  SnsEventToNewrelic:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sns-event-to-newrelic
      CodeUri: sns-event-to-newrelic/
      Handler: main.lambda_handler
      Runtime: python3.8
      Policies:
        - Version: '2012-10-17' 
          Statement:
            Effect: "Allow"
            Action:
              - ssm:GetParameters
            Resource: 
              - { 'Fn::Join': [':', ['arn:aws:ssm', { Ref: 'AWS::Region' } ,{ Ref: 'AWS::AccountId' }, 'parameter/newrelic/*']] }
        - Version: '2012-10-17' 
          Statement:
            Effect: "Allow"
            Action:
              - kms:Decrypt
            Resource:
              - { 'Fn::Join': [':', ['arn:aws:kms', { Ref: 'AWS::Region' } ,{ Ref: 'AWS::AccountId' }, 'keys/*']] }
            Condition:
              StringEquals:
                kms:RequestAlias: "alias/aws/secretsmanager"
      Events:
        AWSRDSEvent:
          Type: SNS
          Properties:
            Topic: !Ref AWSRDSEvent
        AWSElastiCacheEvent:
          Type: SNS
          Properties:
            Topic: !Ref AWSElastiCacheEvent
  AWSRDSEvent:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AWSRDSEvent
  AWSElastiCacheEvent:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AWSElastiCacheEvent
